### ISSUE TITLE
Setting investigations/reinvestigations value on endpoint > 65535 causes faucet to fail

### ISSUE THREAD

**Issue by snak1219** [CyberReboot/poseidon#1370]
![poseidon_bug](https://user-images.githubusercontent.com/22568590/66360093-993a1a00-e92e-11e9-87a8-083312de2e94.png)

This might be more of a faucet issue since faucet is the one that can't handle the value size but setting endpoint investigations > 65535 causes Faucet to fail throwing the below error. 
(check_config on faucet will pass so Last_known_good_config won't run I believe) 

Maybe a quick fix would be just to put up a warning?

`Oct 08 00:53:36 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/faucet/faucet.py", line 178, in _send_flow_msgs
    valve.send_flows(ryu_dp, flow_msgs)
  File "/usr/lib/python3.7/site-packages/faucet/valve.py", line 1796, in send_flows
    ryu_dp.send_msg(flow_msg)
  File "/usr/lib/python3.7/site-packages/ryu/controller/controller.py", line 438, in send_msg
    msg.serialize()
  File "/usr/lib/python3.7/site-packages/ryu/ofproto/ofproto_parser.py", line 270, in serialize
    self._serialize_body()
  File "/usr/lib/python3.7/site-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 2738, in _serialize_body
    self.out_group, self.flags)
  File "/usr/lib/python3.7/site-packages/ryu/lib/pack_utils.py", line 25, in msg_pack_into
    struct.pack_into(fmt, buf, offset, *args)
struct.error: 'H' format requires 0 <= number <= 65535`

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/pull/3283 fixes this on the FAUCET side.

**Comment by snak1219** [comment]
I noticed that this is actually a poseidon issue as well as a poseidon issue. When poseidon sets arp_neighbor_timeout value, it also needs to set L2_timeout (the field is called timeout) greater than arp_neighbor_timeout*2 in the faucet yaml

There is actually no maximum value required by faucet.

**Comment by cglewis** [comment]
@snak1219 poseidon sets timeout to two times the value plus 1 so it should already handle that constraint.
