### ISSUE TITLE
Error on `show what <IP_address>`

### ISSUE THREAD

**Issue by rashley-iqt** [CyberReboot/poseidon#1389]
the command `show what <ip_address>` in the cli results in the error

```
[ERROR] Exception in show_what: 'int' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/poseidon/poseidon/helpers/exception_decor.py", line 19, in wrapper
    return function(*args, **kwargs)
  File "/poseidon/poseidon/cli/cli.py", line 642, in show_what
    nonzero=nonzero, output_format=output_format, ipv4_only=ipv4_only, ipv6_only=ipv6_only, ipv4_and_ipv6=ipv4_and_ipv6))
  File "/poseidon/poseidon/cli/cli.py", line 471, in display_results
    record.append(fields_lookup[field.lower()][0](endpoint))
  File "/poseidon/poseidon/cli/cli.py", line 51, in _get_vlan
    return vlan.split('VLAN')[1] if vlan.startswith('VLAN') else vlan
AttributeError: 'int' object has no attribute 'startswith'

```

**Comment by cglewis** [comment]
fixed with #1390
