### ISSUE TITLE
Pointing .vent_startup.yml to github fork

### ISSUE THREAD

**Issue by jaiken06** [CyberReboot/poseidon#651]
I changed the link pointed to for building PoseidonML in `.vent_startup.yml` to my own fork of PoseidonML however I receive the error:

```
2018-07-03T11:13:41+00:00 172.17.0.1 stupefied_austin/31946bada867/pcap[1494]: Traceback (most recent call last):
2018-07-03T11:13:41+00:00 172.17.0.1 stupefied_austin/31946bada867/pcap[1494]:   File "eval_OneLayer.py", line 354, in <module>
2018-07-03T11:13:41+00:00 172.17.0.1 stupefied_austin/31946bada867/pcap[1494]:     with open(load_path, 'rb') as handle:
2018-07-03T11:13:41+00:00 172.17.0.1 stupefied_austin/31946bada867/pcap[1494]: FileNotFoundError: [Errno 2] No such file or directory: 'models/OneLayerModel.pkl'
2018-07-03T11:13:41+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master3/4830ebe2fb5c/core[1494]: (True, ['cyberreboot-vent-plugins-p0f-master:HEAD', 'jaiken06-poseidonml-nodeclassifier-eval-master:HEAD'])
2018-07-03T11:13:41+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master3/4830ebe2fb5c/core[1494]: 10:13:41 default: Job OK (29672e02-550c-45db-8475-c3b210058f0b)
2018-07-03T11:13:41+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master3/4830ebe2fb5c/core[1494]: 10:13:41 Result is kept for 500 seconds
```

I changed `.vent_startup.yml` to:

```
https://github.com/cyberreboot/vent:
    elasticsearch:
        build: no
        start: no
    file_drop:
        build: yes
        start: yes
    network_tap:
        build: yes
        start: yes
    rabbitmq:
        build: yes
        start: yes
    redis:
        build: yes
        start: yes
    rmq_es_connector:
        build: no
        start: no
    rq_dashboard:
        build: yes
        start: yes
    rq_worker:
        build: yes
        start: yes
        settings:
            instances: 4
    syslog:
        build: yes
        start: yes
https://github.com/cyberreboot/poseidon:
    '@':
        build: yes
        start: yes
    api:
        build: yes
        start: yes
https://github.com/cyberreboot/vent-plugins:
    pcap_to_node_pcap:
        build: yes
    p0f:
        build: yes
    tcprewrite_dot1q:
        build: yes
https://github.com/cyberreboot/crviz:
    '@':
        build: yes
        start: yes
https://github.com/jaiken06/poseidonml:
    nodeclassifier@eval:
        build: yes
vent.cfg:
    build-options:
        use_existing_images: yes
```

This is interesting because I forked without even altering the models directory and it still gave this error.  I then put in my own .pkl and it was still giving this same error.

Why does it need to find OneLayerModel.pkl, could it not just use my own .pkl?  If that is not the case, why would it be unable to find the file in a new fork even though nothing had been altered initially?

Thanks

**Comment by jaiken06** [comment]
I just noticed it is looking for `OneLayerModel.pkl` whereas the actual file is called `OneLayer.pkl`

**Comment by cglewis** [comment]
Can you provide more of the logs before the Traceback?  The `.vent_startup.yml` looks good, and looks like it worked since it built the image against your fork: `jaiken06-poseidonml-nodeclassifier-eval-master:HEAD`.

The name of the `.pkl` file appears to be hardcoded throughout the codebase - an improve should be made there.  As for the model not being found, it looks to me for some reason the argument isn't getting processed so it's falling back to a default path of `models/OneLayerModel.pkl`: https://github.com/CyberReboot/PoseidonML/blob/master/NodeClassifier/eval_OneLayer.py#L351

However, the models are getting mapped into `/models` in the docker container controlled by Vent (https://github.com/CyberReboot/PoseidonML/blob/master/NodeClassifier/eval.template#L12), so it won't find them, since they're in `/NodeClassifier/models` (https://github.com/CyberReboot/PoseidonML/blob/master/NodeClassifier/Dockerfile.eval#L14).  This second case should be corrected to look in the right place if the argument fails, however I'm also curious why the argument failed, so I'd like to see more logs above the `Traceback` to see what happened.

I'll open an issue on `PoseidonML` to fix the path when there isn't an argument.

**Comment by jaiken06** [comment]
So I have fixed my other issue (the faucet.yaml directory one), in the process of doing that I brought down all images etc and essentially started fresh and it seems this problem is now fixed somehow.

Like you say, it is indeed building the image against my fork and I no longer get: 
```
2018-07-03T11:13:41+00:00 172.17.0.1 stupefied_austin/31946bada867/pcap[1494]: Traceback (most recent call last):
2018-07-03T11:13:41+00:00 172.17.0.1 stupefied_austin/31946bada867/pcap[1494]:   File "eval_OneLayer.py", line 354, in <module>
2018-07-03T11:13:41+00:00 172.17.0.1 stupefied_austin/31946bada867/pcap[1494]:     with open(load_path, 'rb') as handle:
2018-07-03T11:13:41+00:00 172.17.0.1 stupefied_austin/31946bada867/pcap[1494]: FileNotFoundError: [Errno 2] No such file or directory: 'models/OneLayerModel.pkl'
```

It is still classifying against the default classifiers that come with Poseidon, do I have to specify for it to use my own pickle?  I have put my .pickle in `NodeClassifer/models`, https://github.com/jaiken06/PoseidonML/tree/master/NodeClassifier/models

How do I get it to classify against the model SecondTrain.pkl? The traffic I am running through should match against it very well rather than the default ones.

**Comment by jaiken06** [comment]
The logs are the following now:

```
2018-07-05T11:54:58+00:00 172.17.0.1 happy_visvesvaraya/d23ff7cf3393/pcap[1421]: {}
2018-07-05T11:54:59+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master3/2cfc71ff112e/core[1421]: (True, ['cyberreboot/vent-plugins-p0f:master', 'jaiken06/poseidonml-nodeclassifier-eval:master'])
2018-07-05T11:54:59+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master3/2cfc71ff112e/core[1421]: 10:54:59 default: Job OK (118ffcdb-b0f6-4a35-84f7-d4501eaf2701)
2018-07-05T11:54:59+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master3/2cfc71ff112e/core[1421]: 10:54:59 Result is kept for 500 seconds
2018-07-05T11:54:59+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master3/2cfc71ff112e/core[1421]: 10:54:59 default: watch.file_queue('4459c1c5a9e6_/files/tcprewrite-dot1q-2018-07-05-10_54_52.946134-UTC/pcap-node-splitter-2018-07-05-10_54_54.003604-UTC/servers/trace_0d00c08a49da6e00feca6f7e7ec29a0b3b946acf_2018-07-05_10_39_51-server-ip-93-184-216-34.pcap') (0a66ccba-42ae-4fa5-90cf-73edc61c3bfd)
2018-07-05T11:54:59+00:00 172.17.0.1 frosty_lamarr/b9c03e74371a/pcap[1421]: {}
2018-07-05T11:54:59+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master3/2cfc71ff112e/core[1421]: Path to manifest: /root/.vent/plugin_manifest.cfg
2018-07-05T11:54:59+00:00 172.17.0.1 relaxed_jennings/cedb9cba29e3/pcap[1421]: {}
2018-07-05T11:55:00+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master4/58d0bfade24c/core[1421]: (True, ['cyberreboot/vent-plugins-p0f:master', 'jaiken06/poseidonml-nodeclassifier-eval:master'])
2018-07-05T11:55:00+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master4/58d0bfade24c/core[1421]: 10:55:00 default: Job OK (2920f887-c1ec-49c1-b71a-d0bba9fbb50f)
2018-07-05T11:55:00+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master4/58d0bfade24c/core[1421]: 10:55:00 Result is kept for 500 seconds
2018-07-05T11:55:00+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master4/58d0bfade24c/core[1421]: 10:55:00 default: watch.file_queue('4459c1c5a9e6_/files/tcprewrite-dot1q-2018-07-05-10_54_52.946134-UTC/pcap-node-splitter-2018-07-05-10_54_54.003604-UTC/servers/trace_0d00c08a49da6e00feca6f7e7ec29a0b3b946acf_2018-07-05_10_39_51-server-ip-138-236-128-36.pcap') (d50e36ca-bb77-4993-b1f1-09d82936ce4e)
2018-07-05T11:55:00+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master4/58d0bfade24c/core[1421]: Path to manifest: /root/.vent/plugin_manifest.cfg
2018-07-05T11:55:01+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master/3dc8dbfee771/core[1421]: 10:55:01 default: Job OK (9e58a6ea-6f74-4f36-99ac-73dcd2c9528e)
2018-07-05T11:55:01+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master/3dc8dbfee771/core[1421]: 10:55:01 Result is kept for 500 seconds
2018-07-05T11:55:01+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master/3dc8dbfee771/core[1421]: (True, ['cyberreboot/vent-plugins-p0f:master', 'jaiken06/poseidonml-nodeclassifier-eval:master'])
2018-07-05T11:55:01+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master/3dc8dbfee771/core[1421]: 10:55:01 default: watch.file_queue('4459c1c5a9e6_/files/tcprewrite-dot1q-2018-07-05-10_54_52.946134-UTC/pcap-node-splitter-2018-07-05-10_54_54.003604-UTC/servers/trace_0d00c08a49da6e00feca6f7e7ec29a0b3b946acf_2018-07-05_10_39_51-server-ip-198-38-16-1.pcap') (acf52c1b-218b-4cef-a512-c3a63f956605)
2018-07-05T11:55:01+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master2/f0b93527988f/core[1421]: (True, ['cyberreboot/vent-plugins-p0f:master', 'jaiken06/poseidonml-nodeclassifier-eval:master'])
2018-07-05T11:55:01+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master2/f0b93527988f/core[1421]: 10:55:01 default: Job OK (3f49ad47-c01c-4570-b107-ba460d094c27)
2018-07-05T11:55:01+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master2/f0b93527988f/core[1421]: 10:55:01 Result is kept for 500 seconds
2018-07-05T11:55:01+00:00 172.17.0.1 cyberreboot-vent-rq-worker-master2/f0b93527988f/core[1421]: 10:55:01 default: watch.file_queue('4459c1c5a9e6_/files/tcprewrite-dot1q-2018-07-05-10_54_52.946134-UTC/pcap-node-splitter-2018-07-05-10_54_54.003604-UTC/servers/trace_0d00c08a49da6e00feca6f7e7ec29a0b3b946acf_2018-07-05_10_39_51-server-ip-208-75-89-4.pcap') (e0cced08-ca7f-40de-80b9-e2b6185841d3)
2018-07-05T11:55:01+00:00 172.17.0.1 upbeat_meitner/d904ffc8ec02/pcap[1421]: {'192.168.1.240': {'short_os': 'Linux', 'full_os': 'Linux 2.2.x-3.x'}}
2018-07-05T11:55:01+00:00 172.17.0.1 pensive_brown/6964e1d23687/pcap[1421]: INFO:__main__:Unknown : 0.575
2018-07-05T11:55:01+00:00 172.17.0.1 pensive_brown/6964e1d23687/pcap[1421]: INFO:__main__:Developer workstation : 0.25
2018-07-05T11:55:01+00:00 172.17.0.1 pensive_brown/6964e1d23687/pcap[1421]: INFO:__main__:GPU laptop : 0.078
2018-07-05T11:55:01+00:00 172.17.0.1 pensive_brown/6964e1d23687/pcap[1421]: INFO:__main__:Message: {"0d00c08a49da6e00feca6f7e7ec29a0b3b946acf": {"timestamp": 1530788088.688442, "valid": true, "decisions": {"investigate": true, "behavior": "normal"}, "classification": {"labels": ["Unknown", "Developer workstation", "GPU laptop"], "confidences": [0.5752115076140932, 0.24989196169150166, 0.07757704822076805]}}}
2018-07-05T11:55:01+00:00 172.17.0.1 pensive_brown/6964e1d23687/pcap[1421]: INFO:pika.adapters.base_connection:Connecting to 172.17.0.3:5672
2018-07-05T11:55:01+00:00 172.17.0.1 pensive_brown/6964e1d23687/pcap[1421]: INFO:pika.adapters.blocking_connection:Created channel=1
2018-07-05T11:55:01+00:00 172.17.0.1 pensive_brown/6964e1d23687/pcap[1421]: INFO:pika.adapters.blocking_connection:Closing connection (200): Normal shutdown
2018-07-05T11:55:01+00:00 172.17.0.1 pensive_brown/6964e1d23687/pcap[1421]: INFO:pika.channel:Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN socket=('172.17.0.16', 60974)->('172.17.0.3', 5672) params=<ConnectionParameters host=rabbit port=5672 virtual_host=/ ssl=False>>>
2018-07-05T11:55:01+00:00 172.17.0.1 pensive_brown/6964e1d23687/pcap[1421]: INFO:pika.channel:Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN socket=('172.17.0.16', 60974)->('172.17.0.3', 5672) params=<ConnectionParameters host=rabbit port=5672 virtual_host=/ ssl=False>>>
2018-07-05T11:55:01+00:00 172.17.0.1 pensive_brown/6964e1d23687/pcap[1421]: INFO:pika.connection:Closing connection (200): Normal shutdown
2018-07-05T11:55:01+00:00 172.17.0.1 pensive_brown/6964e1d23687/pcap[1421]: INFO:pika.connection:Disconnected from RabbitMQ at rabbit:5672 (200): Normal shutdown
2018-07-05T11:55:01+00:00 172.17.0.1 pensive_brown/6964e1d23687/pcap[1421]: INFO:pika.adapters.blocking_connection:Connection closed; result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED socket=None params=<ConnectionParameters host=rabbit port=5672 virtual_host=/ ssl=False>>, reason_code=200, reason_text='Normal shutdown')
```

Which looks about right, I would just like it to use my classifier/labels

**Comment by cglewis** [comment]
currently the path to the model is hardcoded throughout the PoseidonML codebase, so you'd need to name your pickle file the same as the existing one and replace it for it to get picked up.  Please open a feature request on the PoseidonML repo for that here: https://github.com/CyberReboot/PoseidonML/issues

As this particular issue (as noted in the title) is working as expected, I'll close this issue.
